### ISSUE TITLE
Note from Mike Stay on code in tutorial

### ISSUE THREAD

**Issue by KellyatPyrofex** [tschoffelen/rholang-tutorial#1]
Hi, Thomas. Showed your publication of the tutorial to the dev team. They give it a big 👍 

Here's a comment from Mike Stay:
Please also let him know that any code snippet without numbers to the left is incomplete code meant only to get across an idea.

**Comment by tschoffelen** [comment]
Cool, makes sense. I will make sure to remove the run button from those ones somewhere later today.

**Comment by tschoffelen** [comment]
Fixed in 5b25565 - only code examples that originally had line numbers now show a 'Run' button.
